### PR TITLE
Adds a uuid helper function

### PR DESCRIPTION
**Pull request by madmpj**
Adds a uuid helper function for doing uuid() calls

### CODE REVIEW

**Review by jspekken — APPROVED** [review]

**Comment by madmpj** [comment]
This breaks core ; wait a bit :)

**Comment by madmpj** [comment]
added the function uuid() {
}
fixes the fix

**Comment by jspekken** [comment]
In what way does it break core? -edit: nevermind ;)

**Comment by jspekken** [comment]
cleared for takeoff 🌮

**Pull request merged**
